name: Generate Documentation

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Install DocFX
      run: |
        dotnet tool install -g docfx
        echo "${{ github.env.PATH }}:/root/.dotnet/tools" >> $GITHUB_PATH

    - name: Build documentation
      run: |
        docfx docfx.json

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: _site
