name: Update README

on:
  push:
    branches:
      - release

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Read current value from README
      id: read_number
      run: |
        if [ -f README.md ]; then
          number=$(grep -o '[0-9]*' README.md)
          echo "Current number: $number"
        else
          number=0
          echo "Current number: $number (file not found)"
        fi
        echo "::set-output name=current_number::$number"
      
    - name: Increment number
      id: increment_number
      run: |
        new_number=$((${{ steps.read_number.outputs.current_number }} + 1))
        echo "New number: $new_number"
        echo "::set-output name=new_number::$new_number"
      
    - name: Update README.md
      run: |
        echo "${{ steps.increment_number.outputs.new_number }}" > README.md
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Increment README number"
        git push
